### ISSUE TITLE
Command './setup.sh YOURSECRET "dashdb-for-transactions"' partially fails

### ISSUE THREAD

**Issue by lee-zhg** [IBM-Cloud/slack-chatbot-database-watson#11] opened 2020-10-13 21:53 UTC
When running command
   ./setup.sh YOURSECRET "dashdb-for-transactions"

It partially fails. It fails to create table and add sample data. It returns

ok: created namespace slackbot
If you are using any deprecated action runtimes, update them to continue receiving updates and support. Deprecated runtimes might be disabled in future.
For more information see <https://ibm.biz/Functions-Runtimes>
ok: whisk namespace set to slackbot
ok: created package slackdemo
ok: created action slackdemo/db2Setup
Credentials 'slackbotkey' from 'dashdb-for-transactions' service instance 'eventDB' bound to 'slackdemo/db2Setup'.
{
    "dberror": {}
}
{
    "dberror": {}
}
ok: created action slackdemo/dispatch
Credentials 'slackbotkey' from 'dashdb-for-transactions' service instance 'eventDB' bound to 'slackdemo/dispatch'.

**Comment by lee-zhg** [comment] 2020-10-13 23:46
dsn=params.__bx_creds[Object.keys(params.__bx_creds)[0]].dsn;

"dsn" returned by the above code is "undefined"

**Comment by data-henrik** [comment] 2020-10-14 08:05
This is my result. I assume the error you are seeing is related to #10. It could be that provisioning your database service was not successful. Hence you have trouble accessing the Db2 management console and see the error caused by missing credentials.

My recommendation is to recreate the Db2 service, i.e., delete it, then create it again.

```
$ sh setup.sh foobar "dashdb-for-transactions"
ok: created namespace slackbot
If you are using any deprecated action runtimes, update them to continue receiving updates and support. Deprecated runtimes might be disabled in future.
For more information see <https://ibm.biz/Functions-Runtimes>
ok: whisk namespace set to slackbot
ok: created package slackdemo
ok: created action slackdemo/db2Setup
Credentials 'slackbotkey' from 'dashdb-for-transactions' service instance 'eventDB' bound to 'slackdemo/db2Setup'.
{
    "result": []
}
{
    "result": []
}
ok: created action slackdemo/dispatch
Credentials 'slackbotkey' from 'dashdb-for-transactions' service instance 'eventDB' bound to 'slackdemo/dispatch'.
```

**Comment by data-henrik** [comment] 2020-10-14 08:06
I am closing this issue. Please reopen if my recommendation does not solve the issue.

**Closed as completed by data-henrik** 2020-10-14 08:06 UTC
Labels: help wanted

**Comment by lee-zhg** [comment] 2020-10-14 11:52
@data-henrik what data center did you use to provision the DB2 instance when testing? Thank you

**Comment by data-henrik** [comment] 2020-10-14 12:09
@lee-zhg let's communicate via #10

**Comment by lee-zhg** [comment] 2020-10-14 15:17
@data-henrik, This morning I run everything again in IBM Cloud Shell as you did not encounter the same issue. And, I got the same result as I did on my local machine yesterday.

Could you please try it in Cloud Shell? It can ensure we run the process in the same environment. I feel we may have a diff CLI env as we see diff result. I am interesting to see if it works for you in Cloud Shell.
